use crate::{crd::WatchRecord, errors::ControllerError, util};
use futures::StreamExt;
use kube::{
    Api, Client,
    api::{Patch, PatchParams},
    runtime::{controller::Action, watcher},
};
use std::{sync::Arc, time::Duration};

pub struct Context {
    pub client: Client,
}

pub fn create_controller(client: Client) {
    let controller = kube::runtime::Controller::new(
        Api::<WatchRecord>::default_namespaced(client.clone()),
        watcher::Config::default(),
    );
    let context = Arc::new(Context { client });

    tokio::spawn(async move {
        controller
            .run(reconciler, error_policy, context)
            .for_each(|_| async {})
            .await;
    });
}

pub async fn reconciler(
    obj: Arc<WatchRecord>,
    ctx: Arc<Context>,
) -> Result<Action, ControllerError> {
    let wr_namespace = &obj
        .metadata
        .namespace
        .clone()
        .unwrap_or("default".to_string());

    let anime =
        util::get_anime(&ctx.client, &obj)
            .await
            .ok_or(ControllerError::AnimeNotFound(
                obj.spec.anime_ref.clone().name,
            ))?;

    let total_eps = anime
        .spec
        .total_episodes
        .expect("Generated by mutating webhook");

    let new_status = util::calc_watch_state(&obj, total_eps);
    let patch = serde_json::json!({ "status": { "watchState": new_status } });

    Api::<WatchRecord>::namespaced(ctx.client.clone(), wr_namespace)
        .patch_status(
            obj.metadata
                .name
                .as_ref()
                .ok_or(ControllerError::WatchRecordNameNotFound)?,
            &PatchParams::default(),
            &Patch::Merge(patch),
        )
        .await
        .map_err(|_| ControllerError::StatusUpdate)?;

    Ok(Action::requeue(Duration::from_secs(1800)))
}

fn error_policy(_: Arc<WatchRecord>, _: &ControllerError, _: Arc<Context>) -> Action {
    Action::requeue(Duration::from_secs(5))
}
