use crate::{crd::WatchRecord, errors::ControllerError, util};
use futures::StreamExt;
use kube::{
    Api, Client,
    api::{Patch, PatchParams},
    runtime::{controller::Action, watcher},
};
use std::{sync::Arc, time::Duration};
use tracing::{debug, error, info, warn};

pub struct Context {
    pub client: Client,
}

pub fn create_controller(client: Client) {
    info!("Initializing WatchRecord controller");
    let controller = kube::runtime::Controller::new(
        Api::<WatchRecord>::default_namespaced(client.clone()),
        watcher::Config::default(),
    );
    let context = Arc::new(Context { client });

    tokio::spawn(async move {
        controller
            .run(reconciler, error_policy, context)
            .for_each(|event| async move {
                match event {
                    Ok((obj_ref, action)) => {
                        debug!(?obj_ref, ?action, "Reconciled WatchRecord");
                    }
                    Err(err) => {
                        error!(error = %err, "Controller reconcile loop failed");
                    }
                }
            })
            .await;
    });
}

pub async fn reconciler(
    obj: Arc<WatchRecord>,
    ctx: Arc<Context>,
) -> Result<Action, ControllerError> {
    let wr_namespace = &obj
        .metadata
        .namespace
        .clone()
        .unwrap_or("default".to_string());

    let anime = util::get_anime(&ctx.client, &obj)
        .await
        .ok_or(ControllerError::AnimeNotFound(
            obj.spec.anime_ref.clone().name,
        ))?;

    let total_eps = anime
        .spec
        .total_episodes
        .expect("Generated by mutating webhook");

    let new_status = util::calc_watch_state(&obj, total_eps);
    let patch = serde_json::json!({ "status": { "watchState": new_status } });

    Api::<WatchRecord>::namespaced(ctx.client.clone(), wr_namespace)
        .patch_status(
            obj.metadata
                .name
                .as_ref()
                .ok_or(ControllerError::WatchRecordNameNotFound)?,
            &PatchParams::default(),
            &Patch::Merge(patch),
        )
        .await
        .map_err(|_| ControllerError::StatusUpdate)?;

    debug!(namespace = %wr_namespace, "WatchRecord status patched");

    Ok(Action::requeue(Duration::from_secs(1800)))
}

fn error_policy(obj: Arc<WatchRecord>, err: &ControllerError, _: Arc<Context>) -> Action {
    warn!(
        name = obj.metadata.name.as_deref().unwrap_or("<unknown>"),
        namespace = obj.metadata.namespace.as_deref().unwrap_or("default"),
        error = %err,
        "Reconcile error; requeueing soon"
    );
    Action::requeue(Duration::from_secs(5))
}
