use crate::{
    anime_api,
    crd::{Anime, WatchRecord},
    errors::{MutationError, ValidationError},
    util,
};
use axum::{Json, Router, extract, routing::post};
use json_patch::Patch;
use kube::{
    Client,
    api::DynamicObject,
    core::admission::{AdmissionRequest, AdmissionResponse, AdmissionReview, Operation},
};
use tracing::{error, info, warn};

pub async fn create_router(client: Client) -> Router {
    let state = client;

    Router::new()
        .route("/mutate", post(mutation_handler))
        .route("/validate", post(validation_handler))
        .with_state(state)
}

async fn validation_handler(
    extract::State(client): extract::State<Client>,
    extract::Json(payload): extract::Json<AdmissionReview<WatchRecord>>,
) -> Json<AdmissionReview<DynamicObject>> {
    let req: AdmissionRequest<WatchRecord> = match payload.try_into() {
        Ok(r) => r,
        Err(e) => {
            error!(error = %e, "Failed to parse validation admission review");
            let rev = AdmissionResponse::invalid(e.to_string()).into_review();
            return Json(rev);
        }
    };

    let mut resp = AdmissionResponse::from(&req);

    if (req.operation == Operation::Create || req.operation == Operation::Update)
        && let Err(e) = validate_watch_record(req.object, &client).await
    {
        warn!(error = %e, "Validation denied");
        resp = resp.deny(e.to_string());
    }

    let review = resp.into_review();

    Json(review)
}

async fn validate_watch_record(
    wr: Option<WatchRecord>,
    client: &Client,
) -> Result<(), ValidationError> {
    if let Some(wr) = wr {
        let watched_eps = wr.spec.episodes_watched;
        let total_eps = util::get_anime(client, &wr)
            .await
            .ok_or(ValidationError::AnimeNotFound)
            .map(|a| {
                a.spec
                    .total_episodes
                    .expect("Generated by mutating webhook")
            })?;

        return if watched_eps <= 0 {
            Err(ValidationError::EpisodeCountTooLow(total_eps, watched_eps))
        } else if watched_eps > total_eps {
            Err(ValidationError::EpisodeCountTooHigh(total_eps, watched_eps))
        } else if watched_eps == total_eps && wr.spec.status.is_some() {
            Err(ValidationError::StatusOverride)
        } else {
            Ok(())
        };
    }

    Err(ValidationError::WatchRecordNotFound)
}

async fn mutation_handler(
    extract::Json(payload): extract::Json<AdmissionReview<Anime>>,
) -> Json<AdmissionReview<DynamicObject>> {
    let req: AdmissionRequest<Anime> = match payload.try_into() {
        Ok(r) => r,
        Err(e) => {
            error!(error = %e, "Failed to parse mutation admission review");
            return Json(AdmissionResponse::invalid(e.to_string()).into_review());
        }
    };

    let resp = match build_mutation_response(&req).await {
        Ok(r) => {
            info!("Mutation patch generated");
            r
        }
        Err(e) => {
            error!(error = %e, "Mutation failed");
            AdmissionResponse::invalid(e.to_string())
        }
    };

    Json(resp.into_review())
}

async fn build_mutation_response(
    req: &AdmissionRequest<Anime>,
) -> Result<AdmissionResponse, MutationError> {
    let mut resp = AdmissionResponse::from(req);

    let obj = req.object.as_ref().ok_or(MutationError::MissingName)?;
    let _name = obj
        .metadata
        .name
        .as_ref()
        .ok_or(MutationError::MissingName)?;

    let new_spec = anime_api::fetch_anime_details(_name)
        .await
        .ok_or(MutationError::AnimeNotFound)?;

    let patch_value = serde_json::json!([
        { "op": "replace", "path": "/spec/englishTitle", "value": new_spec.english_title },
        { "op": "replace", "path": "/spec/japaneseTitle", "value": new_spec.japanese_title },
        { "op": "replace", "path": "/spec/totalEpisodes", "value": new_spec.total_episodes },
        { "op": "replace", "path": "/spec/airingStatus", "value": new_spec.airing_status }
    ]);

    let patch: Patch = serde_json::from_value(patch_value).expect("Patch must be valid, handmade");

    resp = resp
        .with_patch(patch)
        .map_err(|e| MutationError::ApplyPatch(e.to_string()))?;

    Ok(resp)
}
