apiVersion: v1
kind: Namespace
metadata:
  name: kubemal-ns
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubemal-sa
  namespace: kubemal-ns
  annotations:
    argocd.argoproj.io/sync-wave: "0"