apiVersion: v1
kind: Namespace
metadata:
  name: kubemal-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubemal-sa
  namespace: kubemal-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubemal-role
rules:
  - apiGroups: ["kubemal.kofta.app"]
    resources: ["animes", "watchrecords"]
    verbs: ["get", "watch", "update", "list"]
  - apiGroups: ["kubemal.kofta.app"]
    resources: ["watchrecords/status"]
    verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubemal-role
subjects:
  - kind: ServiceAccount
    name: kubemal-sa
    namespace: kubemal-ns
roleRef:
  kind: ClusterRole
  name: kubemal-role
  apiGroup: rbac.authorization.k8s.io
