apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubemal-role
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: ["kubemal.kofta.app"]
    resources: ["animes", "watchrecords"]
    verbs: ["get", "watch", "update", "list", "patch"]
  - apiGroups: ["kubemal.kofta.app"]
    resources: ["watchrecords/status"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubemal-role
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: ServiceAccount
    name: kubemal-sa
    namespace: kubemal-ns
roleRef:
  kind: ClusterRole
  name: kubemal-role
  apiGroup: rbac.authorization.k8s.io
