apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: anime-webook-config
  annotations:
    cert-manager.io/inject-ca-from: kubemal-ns/kubemal-cert
webhooks:
  - name: anime-webhook.kubmal.kofta.app
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      service:
        name: kubemal-service
        namespace: kubemal-ns
    rules:
      - operations: ["CREATE"]
        apiGroups: ["kubemal.kofta.app"]
        apiVersions: ["v1"]
        scope: Namespaced
        resources: ["animes"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: watchrecord-webook-config
  annotations:
    cert-manager.io/inject-ca-from: kubemal-ns/kubemal-cert
webhooks:
  - name: watchrecord-webhook.kubemal.kofta.app
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      service:
        name: kubemal-service
        namespace: kubemal-ns
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["kubemal.kofta.app"]
        apiVersions: ["v1"]
        scope: Namespaced
        resources: ["watchrecords"]
