apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: anime-webook-config
webhooks:
  - name: anime-webhook.kubmal.kofta.app
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      url: "https://tackle-morrison-blackjack-inside.trycloudflare.com/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: ["kubemal.kofta.app"]
        apiVersions: ["v1"]
        scope: Namespaced
        resources: ["animes"]
