name: Build and push image to Docker Hub
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "Dockerfile"
      - ".dockerignore"
      - ".github/workflows/build-push.yaml"

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: |
              kofta/kubemal:latest
              kofta/kubemal:${{ github.sha }}

      - name: Update image tag
        run: |
          sed -i "s|kofta/kubemal:.*|kofta/kubemal:${{ github.sha }}|" \
            kubernetes/deploy/deployment.yaml
          git config user.email "ci@github"
          git config user.name "GitHub Actions"
          git add kubernetes/deploy/deployment.yaml
          git commit -m "chore: update image to ${{ github.sha }}"
          git push
